### ISSUE TITLE
How do loggers that don't support report log this log?

### ISSUE THREAD

**Issue by storyzero** [duct-framework/server.http.jetty#4]
Hello, I'm trying to make duct.logger with [structued-logging](https://github.com/puppetlabs/structured-logging). But structured-logging doesn't support report log level. It seems to come out from timbre. The logger I'm making can't log Jetty start/stop.

How do loggers that don't support report log level log this log?

https://github.com/duct-framework/server.http.jetty/blob/ca0044d8d98e402182e94a825f5a8e7b4b7862a4/src/duct/server/http/jetty.clj#L13

**Comment by weavejester** [comment]
You can substitute `:report` for `:info` in your logger. The report logging level is effectively an info level with higher priority.

**Comment by storyzero** [comment]
Thanks. The logger will substitute :report for :info.
